name: docker hub deploy

on:
  push:
    branches: [ docker_automation ]

jobs:
  fetch-upstream:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Fetch Upstream
      uses: bdougie/fetch-upstream@master
      with:
        upstream: SystemRage/py-kms
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
  build:
    runs-on: ubuntu-latest
    needs: [fetch-upstream]
    steps:
      - uses: actions/checkout@master
      - uses: techpool/docker-build-push@master
        with:
          image: hasechris92/py-kms
          tag: latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          project_path: /home/runner/work/py-kms/py-kms/docker/docker-py3-kms
